{% set name = "sql-metadata" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sql_metadata-{{ version }}.tar.gz
  sha256: 69f9ef71ac69759ae339f0aab6a8a718cf548100d08b742d24bb1800b7a2ea20

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - sqlparse >=0.4.1,<0.5.0

test:
  imports:
    - sql_metadata
  source_files:
    - test
  commands:
    - pip check
    - pytest -v test
  requires:
    - pip
    - pytest

about:
  home: https://github.com/macbre/sql-metadata
  summary: Uses tokenized query returned by python-sqlparse and generates query metadata
  description: |
    Uses tokenized query returned by python-sqlparse and generates query metadata.
    Extracts column names and tables used by the query. Automatically conduct column alias resolution, 
    sub queries aliases resolution as well as tables aliases resolving.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/macbre/sql-metadata/blob/master/README.md
  dev_url: https://github.com/macbre/sql-metadata

extra:
  recipe-maintainers:
    - timkpaine
    - OstapStefakQC
